### ISSUE TITLE
wrong contents in help page 

### ISSUE THREAD

**Issue by bart2001** [one2nc/cloudlens#10]
There are wrong contents in help page.

![image](https://user-images.githubusercontent.com/18025021/225018032-02404ab4-adce-4d56-8b5b-419be59832a0.png)

Some services and aliases are wrong

ec2:s should be EC2 snapshot
ec2:i should be EC2 Image

**Comment by chinmaysomani07** [comment]
Fixed this issue here: [#12 ](https://github.com/one2nc/cloudlens/pull/12)

**Comment by chinmaysomani07** [comment]
Solved this issue in `v0.1.2`
