### ISSUE TITLE
Project status and ECS Support

### ISSUE THREAD

**Issue by flavioelawi** [one2nc/cloudlens#22]
Hello, what is the project status? I see from [this comment](https://github.com/one2nc/cloudlens/issues/2#issuecomment-1459432880) it is in readonly mode.

Would you accept PRs to introduce new services? I have something basic for ECS

**Comment by jdk2588** [comment]
Hello @flavioelawi , thanks for the suggestion. Yes, we working on the project and enhancing the features. 
Can you share what kind of ECS integration you are looking for?

**Comment by flavioelawi** [comment]
Hey @jdk2588 the idea would be to have the same UX as K9s, to be able to drill down from ECS Cluster -> Services -> Tasks -> Containers

Eventually also being able to get a shell in the container via `ecs exec` and `ssm session manager`

I have the basic ECS Cluster view working here https://github.com/one2nc/cloudlens/commit/afe01a7c3060bfa21e3e57685a08c09087d43d83

The support of ECS in cloudlens would extremely benefit people migrating from EKS to ECS and in general a huge quality of life improvement where its not needed to fetch long ARNs and copy paste around.

**Comment by jdk2588** [comment]
Sounds good, please raise the PR! Would be happy to review/get reviews.

**Comment by sualehasif** [comment]
is there an ETA on this. i would absolutely love to help and make this work. i REALLY would love ecs support here.
