### ISSUE TITLE
panic: failed to read profiles -- NO PROFILES FOUND

### ISSUE THREAD

**Issue by sssanjaya** [one2nc/cloudlens#3]
I am using AWS SSO with profiles, but I am getting following errors:

```
cloudlens --profile master                                                                                        
panic: failed to read profiles -- NO PROFILES FOUND

goroutine 1 [running]:
github.com/one2nc/cloudlens/cmd.readAndValidateProfile()
	github.com/one2nc/cloudlens/cmd/root.go:90 +0x228
github.com/one2nc/cloudlens/cmd.run(0x105ad1d00?, {0x10502a704?, 0x2?, 0x2?})
	github.com/one2nc/cloudlens/cmd/root.go:62 +0x1f4
github.com/spf13/cobra.(*Command).execute(0x105ad1d00, {0x14000194190, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x105ad1d00)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/one2nc/cloudlens/cmd.Execute()
	github.com/one2nc/cloudlens/cmd/root.go:42 +0x28
main.main()
	github.com/one2nc/cloudlens/main.go:8 +0x1c
```

aws sts get-caller-identity

Output: 

<img width="900" alt="image" src="https://user-images.githubusercontent.com/17382749/223601893-e1d21934-3de3-4ec9-a5ea-f6c10e4e6d97.png">

**Comment by Shanksg** [comment]
same issue.

**Comment by wonderg** [comment]
The problem exist because cloudlens is searching for access/secret keys only in ~/.aws/config while AWS STS generated keys are stored in ~/.aws/credentials with the following format

[profile_name]
aws_access_key_id        =
aws_secret_access_key    = 
aws_session_token        = 
aws_security_token       = 
x_principal_arn          = 
x_security_token_expires =

**Comment by miguelacaro** [comment]
Same issue here  with profiles

**Comment by chinmay185** [comment]
Ack, thanks for your analysis @wonderg . We are working on fixing this.

**Comment by chinmay185** [comment]
#4 fixes this.
