### ISSUE TITLE
New versions question.

### ISSUE THREAD

**Issue by djadczak-cksource** [one2nc/cloudlens#35]
Hey! 
I noticed the self update works only until the most recent version tag - meaning it's back in time with code from April.
Is it intentional, and you plan a release or an oversight and just needs a bump ?

Thanks in advance! Amazing tool. :)

**Comment by RamanaReddy0M** [comment]
@djadczak-cksource A new version has been released – [v0.1.4](https://github.com/one2nc/cloudlens/releases/tag/v0.1.4). 
Now try using the update mechanism: `cloudlens update`. This will bump the binary version from v0.1.3 to v0.1.4 which is the latest version.
